inherit_from: .rubocop_todo.yml

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Max: 100

Lint/MissingSuper:
  Exclude:
    - spec/support/silence_output.rb

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/MethodLength:
  Max: 15

Naming/HeredocDelimiterNaming:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/RegexpLiteral:
  Exclude:
    - '**/*.gemspec'
    - '**/Guardfile'
